version: '3'
services:
  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/config:/etc/nginx/conf.d
      - ./nginx/log:/var/log/nginx
    networks:
      - elk  
    depends_on:
      - elasticsearch

  logstash:
    image: logstash:7.16.2
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    environment:
      - "ELASTICSEARCH_HOST=elasticsearch"
      - "xpack.monitoring.enabled=false"
      - "ES_JAVA_OPTS=-Xmx256m -Xms256m"
    depends_on:
      - elasticsearch
    networks:
      - elk
    ports:
      - "5044:5044"
      - "9600:9600"
    expose:
      - "5044"

  elasticsearch:
    image: elasticsearch:7.16.1
    environment:
      - "ES_JAVA_OPTS=-Xmx256m -Xms256m"
      - "discovery.type=single-node"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    networks:
      - elk

  kibana:
    image: kibana:7.16.1
    environment:
      - "ELASTICSEARCH_HOSTS=http://elasticsearch:9200"
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    networks:
      - elk

  beats:
    image: elastic/filebeat:7.16.2
    environment:
      - "ELASTICSEARCH_HOSTS=http://elasticsearch:9200"
      - "ELASTICSEARCH_PORT=9200"
    volumes:
      - ./filebeat/config/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./nginx/log:/var/log/nginx
    entrypoint: "filebeat -e -strict.perms=false"
    networks:
      - elk    
    depends_on:
      - elasticsearch
      - nginx
      - logstash
      - kibana
    links:
      - logstash

networks:
  elk:
    driver: bridge
